[project]
name = "an-optimal-rulefit-algorithm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "gurobipy>=13.0.0",
    "numpy>=2.4.1",
    "scikit-learn>=1.8.0",
]
